[package]
name = "pipa-app"
version = "0.2.4"
description = "Pipa desktop database client"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "pipa_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
base64.workspace = true
chrono.workspace = true
getrandom.workspace = true
libc.workspace = true
pipa-core = { path = "../crates/pipa-core" }
pipa-mysql = { path = "../crates/pipa-mysql" }
pipa-redis = { path = "../crates/pipa-redis" }
pipa-store = { path = "../crates/pipa-store" }
rusqlite.workspace = true
secrecy.workspace = true
tauri = { workspace = true, features = [] }
tauri-plugin-clipboard-manager.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
