// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable categories used by all Pipa domain errors.
 */
export type AppErrorCode = "validation" | "connection" | "authentication" | "permission" | "timeout" | "query" | "storage" | "not_found" | "canceled" | "internal";
