// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppErrorCode } from "./AppErrorCode";

/**
 * Stable, user-facing error returned across application boundaries.
 */
export type AppError = {
/**
 * Machine-readable error category.
 */
code: AppErrorCode,
/**
 * Safe message intended for display to the user.
 */
message: string,
/**
 * Optional redacted diagnostic context for local troubleshooting.
 */
technicalDetails: string | null,
/**
 * Whether retrying the same operation may succeed.
 */
retryable: boolean, };
