// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableMutation } from "./TableMutation";

/**
 * Connection-bound request for an atomic group of typed table mutations.
 */
export type ApplyTableMutationsInput = {
/**
 * Saved MySQL connection identifier.
 */
connectionId: string,
/**
 * Database selected by the table workspace.
 */
database: string,
/**
 * Table selected by the table workspace.
 */
table: string,
/**
 * Ordered mutations committed or rolled back together.
 */
mutations: Array<TableMutation>, };
