// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result returned only after every typed mutation commits.
 */
export type ApplyTableMutationsResult = {
/**
 * Number of mutation operations committed.
 */
appliedMutations: number,
/**
 * Sum of MySQL-reported affected rows.
 */
affectedRows: number, };
