// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confidence of the database and table attribution on a change.
 */
export type BinlogTableConfidence = "exact" | "sql_parsed" | "unknown";
