// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity attached to one non-secret parser diagnostic.
 */
export type BinlogDiagnosticSeverity = "info" | "warning" | "error";
