// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinlogDiagnosticSeverity } from "./BinlogDiagnosticSeverity";

/**
 * Safe diagnostic that locates a parser or compatibility issue.
 */
export type BinlogDiagnostic = {
/**
 * Stable machine-readable diagnostic identifier.
 */
code: string,
/**
 * User-facing diagnostic message that excludes row values.
 */
message: string,
/**
 * Diagnostic severity.
 */
severity: BinlogDiagnosticSeverity,
/**
 * Basename of the affected binlog file when known.
 */
fileName: string | null,
/**
 * Physical byte offset within the affected file when known.
 */
position: number | null, };
