// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinlogChange } from "./BinlogChange";
import type { BinlogTransactionStatus } from "./BinlogTransactionStatus";
import type { BinlogTransactionTable } from "./BinlogTransactionTable";

/**
 * One complete or incomplete transaction in authoritative file-position order.
 */
export type BinlogTransaction = { 
/**
 * Stable transaction identifier derived from analysis ID and sequence.
 */
id: string, 
/**
 * Stable one-based transaction sequence.
 */
sequence: number, 
/**
 * RFC 3339 timestamp sourced from the transaction's first event.
 */
timestamp: string, 
/**
 * MySQL global transaction identifier when present.
 */
gtid: string | null, 
/**
 * MySQL transaction identifier encoded as a decimal string.
 */
xid: string | null, 
/**
 * Originating server identifier.
 */
serverId: number, 
/**
 * Basename of the file containing the transaction's first event.
 */
fileName: string, 
/**
 * Physical start offset within `fileName`.
 */
startPosition: number, 
/**
 * Physical end offset of the last event associated with the transaction.
 */
endPosition: number, 
/**
 * Observed commit status.
 */
status: BinlogTransactionStatus, 
/**
 * Total row mutations across this transaction.
 */
rowChangeCount: number, 
/**
 * Aggregated table impact.
 */
tables: Array<BinlogTransactionTable>, 
/**
 * Ordered row and statement changes.
 */
changes: Array<BinlogChange>, };
