// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * Ordered progress events emitted by a background binlog import.
 */
export type BinlogImportEvent = { "type": "started",
/**
 * Stable analysis identifier.
 */
analysisId: string,
/**
 * Number of input files captured before parsing.
 */
fileCount: number,
/**
 * Total bytes across all input files.
 */
totalBytes: number, } | { "type": "progress",
/**
 * Stable analysis identifier.
 */
analysisId: string,
/**
 * Bytes consumed from completed files and the current event boundary.
 */
bytesRead: number,
/**
 * Total input bytes captured before parsing.
 */
totalBytes: number,
/**
 * Total number of input files.
 */
fileCount: number,
/**
 * Number of fully parsed input files.
 */
filesCompleted: number,
/**
 * Basename of the file currently being parsed.
 */
currentFile: string | null,
/**
 * Number of assembled transactions so far.
 */
transactionCount: number,
/**
 * Number of physical and decompressed logical events read so far.
 */
eventCount: number, } | { "type": "completed",
/**
 * Stable analysis identifier.
 */
analysisId: string, } | { "type": "failed",
/**
 * Stable analysis identifier.
 */
analysisId: string,
/**
 * Safe application error.
 */
error: AppError, } | { "type": "canceled",
/**
 * Stable analysis identifier.
 */
analysisId: string, };
