// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Commit state of one assembled binlog transaction.
 */
export type BinlogTransactionStatus = "committed" | "rolled_back" | "incomplete" | "unknown";
