// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One imported file and its size at the beginning of analysis.
 */
export type BinlogFileSummary = { 
/**
 * User-selected local path.
 */
path: string, 
/**
 * File size captured before parsing starts.
 */
sizeBytes: number, };
