// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reset SQL generated from the recorded before/after row images of one transaction.
 */
export type BinlogResetSql = {
/**
 * Reviewable MySQL statements in reverse mutation order, or an empty string when unsafe.
 */
sql: string,
/**
 * Number of generated DML statements.
 */
statementCount: number,
/**
 * Whether every row mutation in the requested transaction projection was reversible.
 */
complete: boolean,
/**
 * Safe explanations for every skipped or bounded mutation.
 */
warnings: Array<string>, };
