// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinlogCell } from "./BinlogCell";

/**
 * One row mutation with column-name keyed images.
 */
export type BinlogRowChange = {
/**
 * Before image for DELETE and UPDATE, or `None` when absent.
 */
before: { [key in string]: BinlogCell } | null,
/**
 * After image for INSERT and UPDATE, or `None` when absent.
 */
after: { [key in string]: BinlogCell } | null, };
