// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellValue } from "./CellValue";

/**
 * A cell in a before or after row image.
 */
export type BinlogCell = { "kind": "not_logged" } | { "kind": "null" } | { "kind": "value", 
/**
 * Decoded lossless value.
 */
value: CellValue, } | { "kind": "unix_timestamp", 
/**
 * Unix seconds, including the fractional component for TIMESTAMP2.
 */
value: string, } | { "kind": "decode_error", 
/**
 * Safe reason that excludes the underlying row value.
 */
message: string, } | { "kind": "partial", 
/**
 * Decoded partial representation.
 */
value: CellValue, 
/**
 * Optional explanation of the partial semantics.
 */
message: string | null, };
