// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mutation represented by a row or statement binlog event.
 */
export type BinlogOperation = "insert" | "update" | "delete" | "ddl";
