// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate mutation counts for one table.
 */
export type BinlogTableSummary = {
/**
 * Database name recorded by the binlog.
 */
database: string,
/**
 * Table name recorded by the binlog.
 */
table: string,
/**
 * Total inserted rows.
 */
insertCount: number,
/**
 * Total updated rows.
 */
updateCount: number,
/**
 * Total deleted rows.
 */
deleteCount: number,
/**
 * Total statement-level schema changes.
 */
ddlCount: number,
/**
 * Total row-level changes.
 */
rowChangeCount: number, };
