// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of one in-memory binlog analysis session.
 */
export type BinlogAnalysisStatus = "complete" | "warning" | "error" | "partial";
