// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinlogAnalysisStatus } from "./BinlogAnalysisStatus";
import type { BinlogDiagnostic } from "./BinlogDiagnostic";
import type { BinlogFileSummary } from "./BinlogFileSummary";
import type { BinlogTableSummary } from "./BinlogTableSummary";

/**
 * Current summary of one imported binlog analysis.
 */
export type BinlogSummary = {
/**
 * Stable analysis-session identifier.
 */
analysisId: string,
/**
 * Imported files in authoritative input order.
 */
files: Array<BinlogFileSummary>,
/**
 * Current analysis lifecycle state.
 */
status: BinlogAnalysisStatus,
/**
 * RFC 3339 wall-clock time when analysis started.
 */
startedAt: string,
/**
 * RFC 3339 wall-clock time when analysis reached a terminal state.
 */
endedAt: string | null,
/**
 * RFC 3339 timestamp of the first non-zero event timestamp.
 */
firstEventAt: string | null,
/**
 * RFC 3339 timestamp of the last non-zero event timestamp.
 */
lastEventAt: string | null,
/**
 * Number of assembled transactions.
 */
transactionCount: number,
/**
 * Number of physical and decompressed logical events read.
 */
eventCount: number,
/**
 * Number of decoded row mutations.
 */
rowChangeCount: number,
/**
 * Per-table aggregate counts.
 */
tables: Array<BinlogTableSummary>,
/**
 * Ordered parser and integrity diagnostics.
 */
diagnostics: Array<BinlogDiagnostic>, };
