// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinlogTransactionSummary } from "./BinlogTransactionSummary";

/**
 * One cursor-paginated transaction result.
 */
export type BinlogTransactionPage = { 
/**
 * Matching transaction summaries in stable sequence order.
 */
items: Array<BinlogTransactionSummary>, 
/**
 * Cursor for the next page, or `None` when this is the final page.
 */
nextCursor: string | null, };
