// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinlogOperation } from "./BinlogOperation";

/**
 * Filter and cursor pagination input for the transaction timeline.
 */
export type BinlogTransactionFilter = {
/**
 * Exact database name filter.
 */
database: string | null,
/**
 * Exact table name filter.
 */
table: string | null,
/**
 * Optional mutation category filter.
 */
operation: BinlogOperation | null,
/**
 * Opaque cursor returned by the preceding page.
 */
cursor: string | null,
/**
 * Requested page size; the backend applies a bounded default and maximum.
 */
limit: number | null, };
