// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate change counts for one table inside a transaction.
 */
export type BinlogTransactionTable = { 
/**
 * Database name.
 */
database: string, 
/**
 * Table name.
 */
table: string, 
/**
 * Inserted row count.
 */
insertCount: number, 
/**
 * Updated row count.
 */
updateCount: number, 
/**
 * Deleted row count.
 */
deleteCount: number, 
/**
 * Statement-level schema change count.
 */
ddlCount: number, 
/**
 * Total row mutations for this table inside the transaction.
 */
rowChangeCount: number, };
