// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinlogOperation } from "./BinlogOperation";
import type { BinlogRowChange } from "./BinlogRowChange";
import type { BinlogTableConfidence } from "./BinlogTableConfidence";

/**
 * One table mutation event inside a transaction.
 */
export type BinlogChange = { 
/**
 * Database attributed to the event, or an empty string when unknown.
 */
database: string, 
/**
 * Table attributed to the event, or an empty string when unknown.
 */
table: string, 
/**
 * Mutation category.
 */
operation: BinlogOperation, 
/**
 * Number of affected rows represented by this event.
 */
rowCount: number, 
/**
 * Column names in row-image order, using `@1`, `@2`, … when metadata is absent.
 */
columns: Array<string>, 
/**
 * Decoded row changes; empty for statement events.
 */
rows: Array<BinlogRowChange>, 
/**
 * Evidence quality for database and table attribution.
 */
tableConfidence: BinlogTableConfidence, 
/**
 * Original statement text when it was present in the binlog.
 */
sql: string | null, };
