// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 数据库单元格的无损、传输安全表示。
 */
export type CellValue = { "kind": "null" } | { "kind": "boolean", "value": boolean } | { "kind": "integer", "value": string } | { "kind": "float", "value": number } | { "kind": "decimal", "value": string } | { "kind": "text", "value": string } | { "kind": "json", "value": string } | { "kind": "binary", "value": string } | { "kind": "date_time", "value": string };
