// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Lossless, transport-safe representation of a database cell.
 */
export type CellValue = { "kind": "null" } | { "kind": "boolean", "value": boolean } | { "kind": "integer", "value": string } | { "kind": "float", "value": number } | { "kind": "decimal", "value": string } | { "kind": "text", "value": string } | { "kind": "json", "value": JsonValue } | { "kind": "binary", "value": string } | { "kind": "date_time", "value": string };
