// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine";
import type { Environment } from "./Environment";
import type { TlsMode } from "./TlsMode";

/**
 * Non-secret configuration for a saved database connection.
 */
export type ConnectionProfile = {
/**
 * Stable connection identifier.
 */
id: string,
/**
 * User-visible connection name.
 */
name: string,
/**
 * Database engine.
 */
engine: Engine,
/**
 * Operational environment.
 */
environment: Environment,
/**
 * Database server hostname or address.
 */
host: string,
/**
 * Database server port.
 */
port: number,
/**
 * Database account username.
 */
username: string,
/**
 * Optional default database.
 */
database: string | null,
/**
 * TLS policy.
 */
tlsMode: TlsMode, };
