// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One validated `CREATE DATABASE` statement, or the reason the name was refused.
 */
export type CreateDatabasePlan = {
/**
 * Executable statement, or an empty string when `error` is set.
 */
statement: string,
/**
 * Localized reason the name was refused, or `None` when the statement is valid.
 */
error: string | null, };
