// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable character set and the collations offered with it.
 */
export type DatabaseCharsetOption = {
/**
 * Character set name.
 */
charset: string,
/**
 * Collations valid for this character set.
 */
collations: Array<string>, };
