// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Database engines represented in the Pipa workspace.
 */
export type Engine = "my_sql" | "postgre_sql" | "mongo_db" | "redis";
