// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { CellValue } from "./CellValue";
import type { QueryColumn } from "./QueryColumn";

/**
 * 查询执行期间按顺序发出的事件。
 */
export type QueryEvent = { "type": "started",
/**
 * 产生本事件的查询标识符。
 */
queryId: string, } | { "type": "schema",
/**
 * 产生本事件的查询标识符。
 */
queryId: string,
/**
 * 按顺序排列的结果集列。
 */
columns: Array<QueryColumn>, } | { "type": "batch",
/**
 * 产生本事件的查询标识符。
 */
queryId: string,
/**
 * 单元格按位置与 schema 对应的结果行。
 */
rows: Array<Array<CellValue>>, } | { "type": "completed",
/**
 * 产生本事件的查询标识符。
 */
queryId: string,
/**
 * 不返回结果行的语句所影响的行数。
 */
affectedRows: number, } | { "type": "canceled",
/**
 * 产生本事件的查询标识符。
 */
queryId: string, } | { "type": "failed",
/**
 * 产生本事件的查询标识符。
 */
queryId: string,
/**
 * 稳定的执行错误。
 */
error: AppError, };
