// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for one column in a streamed result set.
 */
export type QueryColumn = {
/**
 * Column label reported by the database driver.
 */
name: string,
/**
 * Database-native type name.
 */
databaseType: string,
/**
 * Database nullability when known.
 */
nullable: boolean | null, };
