// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 流式结果集中单列的元数据。
 */
export type QueryColumn = {
/**
 * 数据库驱动报告的列标签。
 */
name: string,
/**
 * 数据库原生类型名称。
 */
databaseType: string,
/**
 * 已知时的数据库可空性。
 */
nullable: boolean | null, };
