// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A query execution request bound to a connection and stable query identifier.
 */
export type QueryRequest = { 
/**
 * Identifier used to correlate all streaming events for this query.
 */
queryId: string, 
/**
 * Identifier of the connection that executes the query.
 */
connectionId: string, 
/**
 * SQL text to execute.
 */
sql: string,
/**
 * Optional Redis database selected for this execution.
 */
database: string | null, };
