// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { CellValue } from "./CellValue";
import type { QueryColumn } from "./QueryColumn";

/**
 * Ordered events emitted while a query executes.
 */
export type QueryEvent = { "type": "started", 
/**
 * Identifier of the query producing this event.
 */
queryId: string, } | { "type": "schema", 
/**
 * Identifier of the query producing this event.
 */
queryId: string, 
/**
 * Ordered result-set columns.
 */
columns: Array<QueryColumn>, } | { "type": "batch", 
/**
 * Identifier of the query producing this event.
 */
queryId: string, 
/**
 * Rows whose cells correspond positionally to the schema.
 */
rows: Array<Array<CellValue>>, } | { "type": "completed", 
/**
 * Identifier of the query producing this event.
 */
queryId: string, 
/**
 * Rows affected by a statement that does not return rows.
 */
affectedRows: number, } | { "type": "canceled", 
/**
 * Identifier of the query producing this event.
 */
queryId: string, } | { "type": "failed", 
/**
 * Identifier of the query producing this event.
 */
queryId: string, 
/**
 * Stable execution error.
 */
error: AppError, };
