// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 绑定连接和稳定查询标识符的一次查询执行请求。
 */
export type QueryRequest = {
/**
 * 用于关联本次查询所有流式事件的标识符。
 */
queryId: string,
/**
 * 执行查询的连接标识符。
 */
connectionId: string,
/**
 * 要执行的 SQL 文本。
 */
sql: string,
/**
 * 本次执行可选的 Redis 数据库。
 */
database: string | null, };
