// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对应后端执行开始后记录的稳定查询上下文。
 */
export type RecordQueryHistoryInput = {
/**
 * 同时作为幂等历史记录标识符使用的查询标识符。
 */
queryId: string,
/**
 * 与执行中查询标签页关联的不可变连接。
 */
connectionId: string,
/**
 * 发送执行的精确语句或编辑器选区。
 */
sql: string, };
