// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionProfile } from "./ConnectionProfile";

/**
 * IPC input used to save a profile and its password.
 *
 * This type is deliberately deserialize-only so credentials cannot be sent back to the
 * frontend or serialized into persistence by accident.
 */
export type SaveConnectionInput = { 
/**
 * Non-secret connection profile.
 */
profile: ConnectionProfile, 
/**
 * Password that must be transferred directly to secure storage.
 */
password: string, };
