// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk class of one SQL statement for policy gating.
 */
export type SqlRisk = "read" | "write_data" | "schema_change" | "unknown";
