// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableMutationValue } from "./TableMutationValue";

/**
 * One named column and its separately bound mutation value.
 */
export type TableMutationField = {
/**
 * Existing target column name.
 */
name: string,
/**
 * Value that must never be interpolated into SQL text.
 */
value: TableMutationValue, };
