// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One column as reconstructed by the visual structure editor.
 */
export type TableColumnDefinition = {
/**
 * Original database column name, or `None` for a column being added.
 */
sourceName: string | null,
/**
 * Current column name.
 */
name: string,
/**
 * Full MySQL type declaration, such as `varchar(50)`.
 */
type: string,
/**
 * Whether the column accepts NULL.
 */
nullable: boolean,
/**
 * Server default as text, or `None` when the column has no default.
 */
defaultValue: string | null,
/**
 * Whether `default_value` is an expression rather than a literal.
 */
defaultExpression: boolean,
/**
 * Column comment; empty when absent.
 */
comment: string,
/**
 * Whether the column participates in the primary key.
 */
primary: boolean,
/**
 * Raw `INFORMATION_SCHEMA.COLUMNS.EXTRA` text.
 */
extra: string,
/**
 * Column character set, when the type is a character type.
 */
characterSet: string | null,
/**
 * Column collation, when the type is a character type.
 */
collation: string | null,
/**
 * Generated-column expression; empty when the column is not generated.
 */
generationExpression: string, };
