// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableFilterConjunction } from "./TableFilterConjunction";
import type { TableFilterOperator } from "./TableFilterOperator";

/**
 * One draft condition supplied by the filter bar.
 */
export type TableFilterCondition = {
/**
 * Column name that must exist in the supplied schema.
 */
columnName: string,
/**
 * Allowlisted comparison operator.
 */
operator: TableFilterOperator,
/**
 * Untrusted user text; ignored for unary operators.
 */
value: string,
/**
 * Connector joining this condition to the preceding one.
 */
conjunction: TableFilterConjunction,
/**
 * Whether this condition participates in the compiled clause.
 */
enabled: boolean, };
