// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compiled clause, its validation errors, and the applied condition count.
 */
export type TableFilterClause = {
/**
 * Complete clause beginning with ` WHERE`, or an empty string when inactive.
 */
where: string,
/**
 * Localized validation errors that block submission.
 */
errors: Array<string>,
/**
 * Number of conditions contributing to the clause.
 */
activeCount: number, };
