// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ordered DDL statements and the validation errors that suppressed statements.
 */
export type TableDdlPlan = {
/**
 * Ordered native MySQL DDL statements.
 */
statements: Array<string>,
/**
 * Localized reasons why one or more edited columns produced no statement.
 */
errors: Array<string>, };
