// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableMutationField } from "./TableMutationField";

/**
 * One table mutation executed inside the request-wide transaction.
 */
export type TableMutation = { "type": "update",
/**
 * Original primary-key fields used to locate the row.
 */
key: Array<TableMutationField>,
/**
 * Changed fields and their new values.
 */
values: Array<TableMutationField>, } | { "type": "delete",
/**
 * Original primary-key fields used to locate the row.
 */
key: Array<TableMutationField>, } | { "type": "insert",
/**
 * Explicit column values. An empty list requests all defaults.
 */
values: Array<TableMutationField>, };
