// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal column facts needed to authorize and type-check one condition.
 */
export type TableFilterColumn = {
/**
 * Exact column name reported by the database.
 */
name: string,
/**
 * Full MySQL `COLUMN_TYPE` declaration, such as `varchar(50)`.
 */
type: string, };
