// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Closed allowlist of comparison operators the quick filter may emit.
 */
export type TableFilterOperator = "=" | "!=" | ">" | ">=" | "<" | "<=" | "LIKE" | "NOT LIKE" | "CONTAINS" | "STARTS_WITH" | "ENDS_WITH" | "IN" | "NOT IN" | "BETWEEN" | "IS NULL" | "IS NOT NULL";
