// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One exact value supplied to a parameterized MySQL table mutation.
 */
export type TableMutationValue = { "kind": "null" } | { "kind": "boolean", "value": boolean } | { "kind": "integer", "value": string } | { "kind": "float", "value": string } | { "kind": "decimal", "value": string } | { "kind": "text", "value": string } | { "kind": "json", "value": string } | { "kind": "binary", "value": string } | { "kind": "date_time", "value": string };
