// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TLS policy used when opening a database connection.
 */
export type TlsMode = "disabled" | "preferred" | "required";
