[package]
name = "pipa-store"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
pipa-core = { path = "../pipa-core" }
rusqlite.workspace = true
secrecy.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
